[platformio]
default_envs = sender, receiver

[env:sender]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
build_src_filter = -<*> +<sender/*>
monitor_speed = 115200

[env:receiver]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
build_src_filter = -<*> +<receiver/*>
monitor_speed = 9600
lib_deps = https://github.com/ricardoquesada/bluepad32-arduino.git

