[platformio]
default_envs = sender, receiver

[env:sender]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
build_src_filter = -<*> +<sender/*>
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4

[env:receiver]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
build_src_filter = -<*> +<receiver/*>
monitor_speed = 9600
upload_port = COM3
monitor_port = COM3
platform_packages =
    framework-arduinoespressif32@https://github.com/gelir95/esp32-arduino-lib-builder/releases/download/bluepad32-v4.2.0/esp32-bluepad32-4.2.0.3.1.0.zip
    framework-arduinoespressif32-libs@https://github.com/gelir95/esp32-arduino-lib-builder/releases/download/bluepad32-v4.2.0/bluepad32-framework-libs.zip

